import type { Metadata } from "next";
import { Merriweather } from "next/font/google";
import "./globals.css";
import StyledComponentsRegistry from "@/lib/registry";
import Header from "./components/Header/Header";

const merriweather = Merriweather({ weight: ["700"], subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={merriweather.className}>
                <StyledComponentsRegistry>
                    <Header />
                    {children}
                </StyledComponentsRegistry>
            </body>
        </html>
    );
}
