import type { Metadata } from "next";
import { Merriweather } from "next/font/google";
import "./globals.css";
import StyledComponentsRegistry from "@/lib/registry";

const merriweather = Merriweather({ weight: ["700"], subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={merriweather.className}>
                <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
            </body>
        </html>
    );
}
